### ISSUE TITLE
a11y : surcharger les roles implicites (banner, main, contentinfo...)

### ISSUE THREAD

**Issue by alexisben** [noesya/osuny-hugo-theme-aaa#104]

**Comment by Olivia206** [comment]
[critère 12.6](https://accessibilite.numerique.gouv.fr/methode/criteres-et-tests/#12.6)

**Comment by Olivia206** [comment]
Selon ARIA, il ne faut pas surcharger : [Landmark Regions](https://www.w3.org/WAI/ARIA/apg/practices/landmark-regions/#generalprinciplesoflandmarkdesign)
