### ISSUE TITLE
Pb de li

### ISSUE THREAD

**Issue by arnaudlevy** [noesya/osuny-hugo-theme-aaa#108]
<img width="733" alt="image" src="https://user-images.githubusercontent.com/2088968/228162292-497c24db-970a-4239-8a03-95de3c5923d4.png">

https://bordeauxmontaigne-sida.netlify.app/

**Comment by alexisben** [comment]
Je n'ai pas l'erreur dans w3c ? c'est sur la home ?

**Comment by arnaudlevy** [comment]
Pas reproduit non plus, c'était avec lighthouse. Je close.
