### ISSUE TITLE
Rétro-compatibilité

### ISSUE THREAD

**Issue by alexisben** [noesya/osuny-hugo-theme-aaa#11]
## CSS Grid

- https://www.smashingmagazine.com/2017/11/css-grid-supporting-browsers-without-grid/
- https://github.com/FremyCompany/css-grid-polyfill

## Details & Summary

- https://caniuse.com/?search=details

**Comment by arnaudlevy** [comment]
Quel est le résultat sans polyfill?

**Comment by arnaudlevy** [comment]
Déjà faisons des screenshots sur les plus vieux browsers possibles sur Browserstack @alexisben

**Comment by arnaudlevy** [comment]
Les mettre là : https://www.osuny.org/fonctionnalites/informations-techniques/retrocompatibilite/
