### ISSUE TITLE
Finir la gestion de la position paramétrable du résumé

### ISSUE THREAD

**Issue by arnaudlevy** [noesya/osuny-hugo-theme-aaa#115]
- [x] Formations
- [x] Diplômes
- [x] Publications

https://github.com/noesya/osuny-hugo-theme-aaa/pull/114

**Comment by arnaudlevy** [comment]
Le format lead devrait caractériser le lead dans une page avec sidebar et le lead dans le hero.
Aujourd'hui, il caractérise le lead dans le content en full-width (très gros).
Ce lead devrait nommé lead-full-width.

- `lead-sidebar` -> `lead`
- `lead` -> `lead-full-width`

**Comment by alexisben** [comment]
et retirer le mixin et les variables ```lead-hero```

**Comment by arnaudlevy** [comment]
Il reste vraiment des choses à faire ?

**Comment by arnaudlevy** [comment]
Est-ce qu'on peut clore @alexisben @Olivia206 ?

**Comment by alexisben** [comment]
https://github.com/noesya/osuny-hugo-theme-aaa/issues/205
