### ISSUE TITLE
Vérification sites Osuny

### ISSUE THREAD

**Issue by perrinejoly** [noesya/osuny-hugo-theme-aaa#129]
## WORKS NOESYA 
- [x] https://works.noesya.coop/actualites/2022-11-01-extension-ecogestes/
dans la présentation des projets espacement des logos (beaucoup de blanc)

## VINCENT GAMBARDELLA
- [x] https://www.vincentgambardella.com/articles/
footer trop haut sur les pages vides (cf : page articles)

## UNITEU 
- [x] https://uniteu.netlify.app/
footer : il y a des tirets à côté du mot France

## SINON VIRGULE 
- [x] https://sinonvirgule.netlify.app/projets/
alignement des flèches dans la page projets

**Comment by arnaudlevy** [comment]
Sur Vincent Gambardella, c'est plutôt une utilisation étrange qu'un bug

**Comment by arnaudlevy** [comment]
Sur Unit, ce sont des tirets dans l'adresse de l'école dans l'admin
