### ISSUE TITLE
Surcharge de style sur le héro envoie une erreur

### ISSUE THREAD

**Issue by sachaandre** [noesya/osuny-hugo-theme-aaa#135]
``Dans mon fichier `_configuration.sass` j'ai créé une variable `$color-text-contrast` pour mettre une couleur claire sur un fond foncé (pour notamment le Héro)

En overridant la variable `$hero-color` : 
```
//colors
$color-text-contrast: #ffffff !default

//hero
$hero-color: $color-text-contrast !default
```

La compilation me renvoie l'erreur suivante : 
```
TOCSS: failed to transform "sass/main.sass" (text/x-sass): [1;36m"/Users/sachaandre/Dev/fi-gironde/themes/osuny-hugo-theme-aaa/assets/sass/_theme/design-system/breadcrumb.sass:16:36"[0m: argument `$color` of `rgba($color, $alpha)` must be a color  TOCSS: [1;36m"/Users/sachaandre/Dev/fi-gironde/assets/sass/_configuration.sass:31:14"[0m: overloaded function `rgba` given wrong number of arguments 
```

L'erreur serait donc lié à l'effet de lien qu'il y a sur le fil d'Ariane, qui reprend la même couleur que la variable `$hero-color`

Question(s) : 

- En Sass est-il bien possible d'indiquer dans la fonction rgba une couleur en hexadécimal ?
- Pourquoi tout roule avec la variable de base `$color-text` qui elle aussi est en hexadécimal, mais pas avec une variable nouvellement créée ?

**Comment by alexisben** [comment]
Hello @sachaandre !

Étrange, le rgba en sass devrait prendre du hexa sans soucis, est-ce que tu peux m'envoyer le repo du projet que je regarde stp ?

**Comment by sachaandre** [comment]
Oui bien sur,
Mon repo est le suivant : https://github.com/sachaandre/fi-gironde

**Comment by sachaandre** [comment]
Des news sur l'erreur
J'ai relancé hugo server, l'erreur a disparu
J'imagine une compilation qui n'a pas du se refaire, je ferme l'issur
