### ISSUE TITLE
Empêcher la ponctuation orpheline

### ISSUE THREAD

**Issue by arnaudlevy** [noesya/osuny-hugo-theme-aaa#143]
Remplacer les espaces devant les signes doubles par des insécables

**Comment by arnaudlevy** [comment]
https://github.com/noesya/osuny/pull/1344

**Comment by alexisben** [comment]
Issue pour orthotypo ?

**Comment by arnaudlevy** [comment]
Oui mais @pabois bloque orthotypo

**Comment by arnaudlevy** [comment]
#176
