### ISSUE TITLE
Migration vers la v5.0.0

### ISSUE THREAD

**Issue by arnaudlevy** [noesya/osuny-hugo-theme-aaa#157]
## Contenu de la release
- [x] Renommage “organization_chart” en “people” et “partners” en “organizations”
- [x] Recherche Pagefind
- [x] Refonte blocs (elements)
- [x] Changer le default du summary pour hero
- [x] Package json npx

## Protocole de migration
1. Déploiement accidentel d'une 4.0.7
2. Réparation des sites après renommage @arnaudlevy 
3. Pas de release avant la 5.0.0
4. Merge de pagefind (+ icône) @Olivia206 
5. Développement des elements @Olivia206 
6. Passage sur tous les sites pour modifier le package @arnaudlevy 
7. Vérifier tous les sites en summary `default` et les mettre en `content`

**Comment by alexisben** [comment]
- Chercher dans tous les sites fait avec Osuny, s'il y a des overrides sur les 2 blocks qui ont changés (block people et block organizations) 
- Ces sites là sont concernés (il peut y en avoir plus) : 
      - bordeauxmontaigne
      - coop.noesya.works
      - espeli-site
      - alice
      - classcode
      - codé
      - coop.noesya.lab
      - theme design noesya
      - tactic
      - cepir
      - vigo-internationaldegrowthconference2024

**Comment by alexisben** [comment]
1. S'assurer des modifications (tous les breakpoints et sur un vrai mobile)
2. Release 5.0.0
3. Mettre à jour tous les package.json

**Comment by arnaudlevy** [comment]
Checklist pour un repo : 
- [ ] .gitignore
- [ ] package.json
- [ ] organization_chart -> people
- [ ] partners -> organizations
- [ ] summary 

## Gitignore 
```
/public
.DS_Store
node_modules
/.hugo_build.lock
/.yarn
/resources
/_tmp
jsconfig.json
/static/pagefind
```

## package.json
``` 
{
  "name": "osuny-hugo-template-aaa",
  "version": "2.0.0",
  "repository": "https://github.com/noesya/osuny-hugo-template-aaa",
  "author": "noesya",
  "license": "MIT",
  "dependencies": {
    "osuny-hugo-theme-aaa": "./themes/osuny-hugo-theme-aaa"
  },
  "devDependencies": {
    "autoprefixer": "^10.4.2",
    "postcss": "^8.4.14",
    "postcss-cli": "^9.1.0",
    "postcss-sass": "^0.5.0"
  },
  "scripts": {
    "watch": "npx osuny-hugo-theme watch",
    "build": "npx osuny-hugo-theme build",
    "dev": "npx osuny-hugo-theme dev",
    "update": "npx osuny-hugo-theme update",
    "setup-example": "npx osuny-hugo-theme setup-example",
    "server-example": "npx osuny-hugo-theme server-example",
    "example": "npx osuny-hugo-theme example",
    "update-theme": "npx osuny-hugo-theme update-theme"
  }
}
```

## Summary

Le summary était en default content, il devient default hero.
Il faut donc trouver tous les sites qui ne définissent pas summary en hero, et définir explicitement summary en content

**Comment by arnaudlevy** [comment]
Liste de sites faits : 
- [x] https://www.iut.u-bordeaux-montaigne.fr/
- [x] https://publications.arnaudlevy.com/
- [x] https://www.a11yuniversites.org
