### ISSUE TITLE
L'icône search est trop haute sur la ligne

### ISSUE THREAD

**Issue by arnaudlevy** [noesya/osuny-hugo-theme-aaa#169]
https://rennes-nr.web.deuxfleurs.fr/
<img width="571" alt="Capture d’écran 2023-10-24 à 09 02 00" src="https://github.com/noesya/osuny-hugo-theme-aaa/assets/2088968/5baf3ac6-1d48-4ed1-9e52-33b77ca9280b">

**Comment by arnaudlevy** [comment]
Maintenant ce n'est plus le cas, c'est normal ? 
@Olivia206 tu peux enquêter stp ?

**Comment by Olivia206** [comment]
J'ai fix

**Comment by arnaudlevy** [comment]
Merci :)
