### ISSUE TITLE
Finir l'article "Les défauts des images par défaut"

### ISSUE THREAD

**Issue by arnaudlevy** [noesya/osuny-hugo-theme-aaa#174]
https://docs.google.com/document/d/12s6GQHSg6HKaCtTS9BPg1oLyE-t52VxlA1JshRnN0oM/edit#heading=h.4jjdu5gvqz0x

**Comment by alexisben** [comment]
Article terminé, plus qu'à publier !

**Comment by Olivia206** [comment]
[publié](https://lab.noesya.coop/publications/2023-12-14-les-defauts-des-images-par-defaut/)
