### ISSUE TITLE
Il manque les marges

### ISSUE THREAD

**Issue by arnaudlevy** [noesya/osuny-hugo-theme-aaa#182]
https://ran-coper.fr/initiatives/

<img width="375" alt="Capture d’écran 2023-10-31 à 15 19 17" src="https://github.com/noesya/osuny-hugo-theme-aaa/assets/2088968/57774e7b-d6e8-4cc8-adda-2744fb6b2f22">

**Comment by arnaudlevy** [comment]
Et c'est supposé être cliquable (j'ai checké) mais ça ne l'est pas

**Comment by Olivia206** [comment]
C'est [fix](https://github.com/noesya/osuny-hugo-theme-aaa/commit/c2015aa1426eb40471f0dd75dd9178706b003f3c)

**Comment by arnaudlevy** [comment]
Quand je regarde en prod, je n'ai pas les marges, ni la carte cliquable. Tu as déployé sur Ran Coper @Olivia206 ?

**Comment by Olivia206** [comment]
Mon commit n'est pas passé : [fail](https://github.com/noesya/rancoper-site/actions/runs/6782062763/job/18433543419)
