### ISSUE TITLE
Nouveaux liens de partage 

### ISSUE THREAD

**Issue by Olivia206** [noesya/osuny-hugo-theme-aaa#184]
Dans un post : 
- [x] Liens de partage par défaut : linkedin, facebook
- [x] Liens de partage en + activables dans la config (?) : whatsapp...

**Comment by Olivia206** [comment]
@arnaudlevy  j'ai ajouté whatsapp, telegram et mail, tu en verrais un ou des autre(s) ?

**Comment by arnaudlevy** [comment]
Là comme ça non.
Faut pas que tout soit par défaut.

**Comment by arnaudlevy** [comment]
On peut rester sur X + LinkedIn + FB ?

**Comment by arnaudlevy** [comment]
ah oui tu suggérais LI + FB, c'est bien !

**Comment by Olivia206** [comment]
Oui pour l'instant c'est Linkedin, Facebook et X en défaut, avec Telegram, whatsapp et le mail en option
Les icones ne sont pas très jolies par rapport à celles actuelles, tu valides quand même ?

**Comment by arnaudlevy** [comment]
J'ai pas checké mais il vaut mieux fait que parfait ! Et Violenn est dessus je crois

**Comment by arnaudlevy** [comment]
@Olivia206 tu te souviens qui en voulait ?
