### ISSUE TITLE
Permettre l'ouverture des sous-menus passage de la souris ?

### ISSUE THREAD

**Issue by arnaudlevy** [noesya/osuny-hugo-theme-aaa#190]
Choix dans la config ?

**Comment by alexisben** [comment]
@Olivia206 check pour l'a11y

**Comment by Olivia206** [comment]
Le hover n'est pas accessible au clavier ni lu par les lecteurs d'écran, il faut donc en permanence laisser le clic

**Comment by arnaudlevy** [comment]
ok donc on ne le fait pas.
