### ISSUE TITLE
Respecter les sauts de ligne dans les textes des images du bloc galerie

### ISSUE THREAD

**Issue by arnaudlevy** [noesya/osuny-hugo-theme-aaa#216]
![image](https://github.com/noesya/osuny-hugo-theme-aaa/assets/2088968/4bf21a13-2274-4db1-976c-860169c14bd0)
![image](https://github.com/noesya/osuny-hugo-theme-aaa/assets/2088968/654ddb85-0e58-4a87-b9a5-68ce71b69fd3)

**Comment by alexisben** [comment]
@arnaudlevy Je trouve pas la page sur le site ?

**Comment by arnaudlevy** [comment]
C'était /cellule, de mémoire.
Et le pb était dans les data

**Comment by alexisben** [comment]
Du coup c'est plus un bug ?

**Comment by arnaudlevy** [comment]
C'est tout bon !
