### ISSUE TITLE
Pb de search

### ISSUE THREAD

**Issue by arnaudlevy** [noesya/osuny-hugo-theme-aaa#218]
Sacha nous dit: "pour info sur la recherche MMI sur le site de l'IUT, cet article aveec rien en 1er résultat"

https://www.iut.u-bordeaux-montaigne.fr/

<img width="952" alt="Capture d_e_cran 2023-12-07 a_ 10 59 38" src="https://github.com/noesya/osuny-hugo-theme-aaa/assets/2088968/9742045b-cc45-4172-84a1-818f37b74782">

**Comment by Olivia206** [comment]
Toujours d'actualité ? Je ne vois pas ce résultat
