### ISSUE TITLE
Trop d'espaces entre 2 lignes d'images

### ISSUE THREAD

**Issue by pabois** [noesya/osuny-hugo-theme-aaa#223]
https://www.lilianaoust.fr/les-yeux-de-la-montagne/

<img width="1361" alt="Capture d’écran 2023-12-08 à 16 35 54" src="https://github.com/noesya/osuny-hugo-theme-aaa/assets/2145137/c8129223-432f-4fd7-a2e8-63adef8f8c47">

**Comment by alexisben** [comment]
With some magick...

**Comment by alexisben** [comment]
Non avec une classe supplémentaire (les images ont-elles des crédits ?) et des subgrid css

**Comment by arnaudlevy** [comment]
Trop cool !
