### ISSUE TITLE
Lien mal aligné dans le bloc de métadonnées d'un article

### ISSUE THREAD

**Issue by sachaandre** [noesya/osuny-hugo-theme-aaa#231]
J'ai un nom d'auteur sur 2 lignes, et l'alignement se fait automatiquement à gauche.

<img width="449" alt="Capture d’écran 2023-12-16 à 14 14 51" src="https://github.com/noesya/osuny-hugo-theme-aaa/assets/14942470/c1e391a1-a772-4b7b-a352-6609990cfe31">

**Comment by sachaandre** [comment]
+ Alignement bizarre des icones de RS

**Comment by alexisben** [comment]
Hello @sachaandre ! Merci pour le ticket ! Je fais une PR sur la base de la tienne pour corriger !

**Comment by alexisben** [comment]
Mise à part ça, le nom de l'auteur peut-il être plus court ?

**Comment by alexisben** [comment]
J'ai corrigé ici : https://github.com/noesya/osuny-hugo-theme-aaa/pull/233

Tu peux enlever les overrides sur fi33 normalement tout est ok !

Merci pour ta contrib !

**Comment by sachaandre** [comment]
Je pense que dans mon cas il peut être plus court, mais une personne avec un nom de famille composé peut vite créer ce cas d'usage je pense

**Comment by sachaandre** [comment]
Super, j'avais pas précisé, mais ma PR résolvait aussi un 2e bug d'affichage sur cette infobox : le problème d'alignement des liens de partage RS. Est il possible de le corriger ? (je n'avais pas fait d'override sur le site fi33)

Merci d'avance ! 

<img width="446" alt="Capture d’écran 2023-12-18 à 10 54 26" src="https://github.com/noesya/osuny-hugo-theme-aaa/assets/14942470/7373c613-b6c0-412e-900b-faed9b8f5648">

**Comment by alexisben** [comment]
Oula oui effectivement, sur Chrome c'est ok mais pas du tout sur Firefox ! pourtant j'ai aussi mis l'align-item: center de ta PR. 

Effectivement ça fait des trucs bien chelous si on laisse le padding-right, mais on en a besoin pour laisser la zone de clique de l'icône suffisament grande. Je corrige ça merci ! 


<img width="421" alt="image" src="https://github.com/noesya/osuny-hugo-theme-aaa/assets/4630530/0c0f1e70-1aa0-493d-b14e-00039f0e83e1">

**Comment by alexisben** [comment]
Ok c'est réglé ici : https://github.com/noesya/osuny-hugo-theme-aaa/pull/234 

J'ai mis à jour FI peux-tu me confirmer que c'est ok chez toi ? Merci !

**Comment by sachaandre** [comment]
C'est tout bon ! Merci
