### ISSUE TITLE
[A11Y] Problématique avec Accessibility Toolkit

### ISSUE THREAD

**Issue by Olivia206** [noesya/osuny-hugo-theme-aaa#236]
Problème d'accessibilité détecté par l'extension Accessibility Toolkit : lorsqu'on ouvre une image, la librairie fait header / nav / footer et main en `aria-hidden="true"`. L'extension détecte que le focus continue d'avoir lieu dans ces éléments, mais c'est une erreur : 

![Capture d’écran 2023-12-21 à 10 52 06](https://github.com/noesya/osuny-hugo-theme-aaa/assets/91660674/22f9c231-2fc0-4df1-bba6-2ecb4f285741)

**Comment by arnaudlevy** [comment]
J'ai pas bien compris, mais si c'est une erreur d'analyse de l'extension, OSEF non @Olivia206 ?

**Comment by Olivia206** [comment]
Oui ! On voulait garder une trace du bug
