### ISSUE TITLE
Footer i18n dropdown pas testé en mobile

### ISSUE THREAD

**Issue by alexisben** [noesya/osuny-hugo-theme-aaa#257]
![image](https://github.com/noesya/osuny-hugo-theme-aaa/assets/4630530/7d51acbe-4830-4ebd-8667-98f03e7d218d)

**Comment by Olivia206** [comment]
Est-ce que l'objectif est d'avoir ce rendu : 
![Capture d’écran 2024-02-13 à 11 08 50](https://github.com/noesya/osuny-hugo-theme-aaa/assets/91660674/77181faa-0326-499f-a0f1-da451cb2f378)

Ou est-ce qu'on ne veut pas que le dropdown prenne toute la largeur de l'écran ?

**Comment by arnaudlevy** [comment]
<img width="434" alt="Capture d’écran 2024-02-13 à 17 17 32" src="https://github.com/noesya/osuny-hugo-theme-aaa/assets/2088968/5509d68b-0461-49ac-9d47-60d070e0c198">
