### ISSUE TITLE
Remplacer la collection Article par Paper

### ISSUE THREAD

**Issue by alexisben** [noesya/osuny-hugo-theme-AAA#26]
https://github.com/noesya/osuny/issues/505

**Comment by arnaudlevy** [comment]
Fait dans le thème principal https://github.com/noesya/osuny-hugo-theme/commit/c5da81e7fab794f35863d57311842aa9be3420e3

**Comment by sebousan** [comment]
-> https://github.com/noesya/osuny-hugo-theme-AAA/pull/29
