### ISSUE TITLE
Pb d'espace

### ISSUE THREAD

**Issue by arnaudlevy** [noesya/osuny-hugo-theme-aaa#268]
https://postgrowth-lab.vigo.osuny.site/team/mario-pansera/

<img width="1792" alt="Capture d’écran 2024-02-07 à 08 51 01" src="https://github.com/noesya/osuny-hugo-theme-aaa/assets/2088968/f4558e74-4058-4e32-9911-2cdf3733a41d">

**Comment by arnaudlevy** [comment]
@Olivia206 je comprends pas pourquoi tu close, c'est toujours pas correct en ligne, si ?

**Comment by Olivia206** [comment]
C'est la PR qui a close automatiquement l'issue mais tu as raison, j'aurais dû venir mettre à jour le thème dans la foulée !
En tout cas c'est en ligne maintenant

![Capture d’écran 2024-02-20 à 11 10 44](https://github.com/noesya/osuny-hugo-theme-aaa/assets/91660674/646de8e7-3cf5-43aa-897d-35ba410a315d)
