### ISSUE TITLE
Le lien d'un bloc agenda archives doit aller aux archives

### ISSUE THREAD

**Issue by arnaudlevy** [noesya/osuny-hugo-theme-aaa#269]
https://www.numeriqueinteretgeneral.org/

<img width="1756" alt="Capture d’écran 2024-02-07 à 09 12 08" src="https://github.com/noesya/osuny-hugo-theme-aaa/assets/2088968/e449dbbb-6269-4c10-95e0-49fa7ae48e9f">

**Comment by Olivia206** [comment]
Est-ce qu'on a un moyen de récupérer l'information de la case "Quelles dates d'événements afficher ?" ? Je n'ai pas vu de donnée pour ça dans le fichier statique

**Comment by arnaudlevy** [comment]
Oui je peux te servir ce que tu veux ! 
Peut-être d'ailleurs directement l'url non ?

**Comment by Olivia206** [comment]
C'est une super idée oui, ça évite les calculs côté hugo
