### ISSUE TITLE
Lien problématiques dans Safari

### ISSUE THREAD

**Issue by arnaudlevy** [noesya/osuny-hugo-theme-aaa#30]
https://github.com/noesya/bordeauxmontaigne-iut/issues/31

**Comment by justinpuyo** [comment]
Même problème sur les pages des personnes : 
https://www.iut.u-bordeaux-montaigne.fr/notre-institut/ressources/equipe/cecile-croce/

Lien actif sur tout le header rendant les liens du fil d'ariane inaccessibles

**Comment by alexisben** [comment]
> Même problème sur les pages des personnes : https://www.iut.u-bordeaux-montaigne.fr/notre-institut/ressources/equipe/cecile-croce/
> 
> Lien actif sur tout le header rendant les liens du fil d'ariane inaccessibles

C'est réparé sur le theme bdx montaigne !

**Comment by alexisben** [comment]
Non pas ce ticket là, car pas encore porté sur le AAA

**Comment by arnaudlevy** [comment]
Ok !
