### ISSUE TITLE
Problème de breadcrumb et/ou de path pour les articles

### ISSUE THREAD

**Issue by arnaudlevy** [noesya/osuny-hugo-theme-aaa#33]
https://www.iut.u-bordeaux-montaigne.fr/actualites/2011/07/25/demenagement-du-site-du-campus/

Le breadcrumb est 
```
<nav aria-label="Fil d’arianne">
  <ol itemscope="" itemtype="https://schema.org/BreadcrumbList" class="breadcrumb">
    <li itemprop="itemListElement" itemscope="" itemtype="https://schema.org/ListItem" class="breadcrumb-item">
      <a itemprop="item" href="https://www.iut.u-bordeaux-montaigne.fr/">
        <span itemprop="name">Accueil</span>
      </a>
      <meta itemprop="position" content="4">
    </li>
    <li itemprop="itemListElement" itemscope="" itemtype="https://schema.org/ListItem" class="breadcrumb-item">
      <a itemprop="item" href="https://www.iut.u-bordeaux-montaigne.fr/actualites/">
        <span itemprop="name">Actualités</span>
      </a>
      <meta itemprop="position" content="5">
    </li>
    <li itemprop="itemListElement" itemscope="" itemtype="https://schema.org/ListItem" class="breadcrumb-item active" aria-current="page">
      <span itemprop="name">Tout l’IUT est désormais en centre ville !</span>
      <meta itemprop="position" content="6">
    </li>
  </ol>
</nav>
```

La numérotation 4/5/6 vient de la structure de l'URL, avec année/mois/jour : ce n'est pas parfait. 

Les urls d'année, de mois et de jour ne donnent rien.
2 possibilités :  
- soit on ajoute les pages d'année, de mois, de jour, et donc on aura 1/2/3/4/5/6
- soit on change le schéma d'url, par exemple https://www.iut.u-bordeaux-montaigne.fr/actualites/2011-07-25-demenagement-du-site-du-campus/, pour avoir 1/2/3

**Comment by arnaudlevy** [comment]
@pabois tu en penses quoi ?

**Comment by arnaudlevy** [comment]
@pabois faut que tu te positionnes

**Comment by pabois** [comment]
quitte à choisir je préfère avoir la page année / mois / jour

**Comment by arnaudlevy** [comment]
donc essayer de faire faire ça à Hugo, c'est bien ça ?

**Comment by pabois** [comment]
oui !

**Comment by arnaudlevy** [comment]
https://github.com/gohugoio/hugo/issues/448#issuecomment-360773582
https://github.com/gohugoio/hugo/issues/448#issuecomment-967498216

C'est une demande ouverte depuis 2014, bep n'a pas le temps.
@pabois je suggère que :
- soit tu apprennes golang, et que tu contribues
- soit tu révises ta position et qu'on change le schema d'url (proposition 2)

**Comment by pabois** [comment]
ok, il dit qu'il a plus de genoux...
Go pour changer le schema

**Comment by arnaudlevy** [comment]
Ca marche. Alors il faut d'abord faire la redirection des articles, et gérer l'alias
