### ISSUE TITLE
Problème avec Cloudflare

### ISSUE THREAD

**Issue by arnaudlevy** [noesya/osuny-hugo-theme-aaa#36]
Cloudflare reminifie le js, ce qui cause un sha256 incorrect et bloque le chargement (non intègre).

**Comment by pabois** [comment]
https://community.cloudflare.com/t/disable-minification-with-header/15294/4
https://support.cloudflare.com/hc/en-us/articles/200169876-Why-isn-t-Auto-Minify-working-

en ajoutant un .min(.js) on empêche cloudflare de re-minifier

**Comment by arnaudlevy** [comment]
avec le min avant le sha ça ne fonctionne pas

**Comment by arnaudlevy** [comment]
En attendant j'ai enlevé la vérification d'intégrité
