### ISSUE TITLE
Stretched link dans le block-pages

### ISSUE THREAD

**Issue by Olivia206** [noesya/osuny-hugo-theme-aaa#47]
Le stretched link ne fonctionne pas parce que le lien n'est pas dans le même contenant que la description

![Capture d’écran 2022-12-15 à 17 20 20](https://user-images.githubusercontent.com/91660674/207913355-a1c699fc-5b3a-4304-b16a-cb3a750e6766.png)

**Comment by arnaudlevy** [comment]
s'il s'agit de pouvoir cliquer sur le texte, ce n'est pas souhaitable
