### ISSUE TITLE
Problème d'accessibilité

### ISSUE THREAD

**Issue by arnaudlevy** [noesya/osuny-hugo-theme-aaa#67]
"Quand je navigue au clavier, les élements du menu sont accessibles quand celui-ci est caché."
Pb signalé par [Emmanuel DEMEY](https://www.linkedin.com/in/ACoAAAL4YmEBtU98ke4iZTMo4_mF7nTfkhAgef0)

**Comment by alexisben** [comment]
Pas réussi à reproduire

**Comment by arnaudlevy** [comment]
https://github.com/noesya/coop.noesya.www/issues/5

**Comment by EmmanuelDemey** [comment]
Je viens de faire un petit loom https://www.loom.com/share/eb68bb0b611d4a55801461e943585576

**Comment by arnaudlevy** [comment]
@alexisben @Olivia206

**Comment by alexisben** [comment]
Réparé :) merci !
