### ISSUE TITLE
Vidéos Peertube

### ISSUE THREAD

**Issue by arnaudlevy** [noesya/osuny-hugo-theme-aaa#70]
Il faut que les embed Peertube fonctionnent.

https://www.conviviel.org/actualites/2022-02-16-peertube-etude-des-usages-et-amelioration-de-l-utilisabilite-marie-cecile-godwin/

**Comment by arnaudlevy** [comment]
dans le bloc vidéo on colle l'url complète @SebouChu

**Comment by alexisben** [comment]
Est-ce qu'il faut déterminer la provenance Peertube dans le thème ou en amont dans Osuny ?

**Comment by SebouChu** [comment]
je pense en amont dans Osuny, la majorité des calculs doit se faire côté Osuny pour garder la perf maximale sur la compilation

**Comment by alexisben** [comment]
En attendant, on peut mettre directement une url d'iframe, et ça fallback sur un iframe simple
