### ISSUE TITLE
Changement de colonnage dans le testimonial

### ISSUE THREAD

**Issue by arnaudlevy** [noesya/osuny-hugo-theme-aaa#71]
@alexisben j’ai fait une modif dans Figma sur le block testimonials en full width stp

**Comment by alexisben** [comment]
Masquer le titre du bloc

**Comment by arnaudlevy** [comment]
Oui, et aussi modifier le colonnage (cf https://www.osuny.org, la citation en haut)
Il doit y avoir une colonne vide à gauche
