### ISSUE TITLE
Ajouter une classe css active pour les liens du menu header

### ISSUE THREAD

**Issue by alexisben** [noesya/osuny-hugo-theme-aaa#86]
Ajouter une classe active sur le lien de la page courante dans le menu

**Comment by arnaudlevy** [comment]
Peut-être `{{ $active := in $current.RelPermalink .URL }}`

https://discourse.gohugo.io/t/another-way-to-make-a-menu-item-active/17029/6

**Comment by alexisben** [comment]
Est-ce que j'identifie aussi la page parente ou c'est pas nécessaire ?

![image](https://user-images.githubusercontent.com/4630530/218745182-f12595a0-0567-4db4-9dd1-9da925af6c5d.png)

**Comment by alexisben** [comment]
fixed in https://github.com/noesya/osuny-hugo-theme-aaa/releases/tag/v3.1.6
