### ISSUE TITLE
Faire le balisage schema.org des publications

### ISSUE THREAD

**Issue by arnaudlevy** [noesya/osuny-hugo-theme-aaa#94]
https://schema.org/ScholarlyArticle

**Comment by Olivia206** [comment]
@arnaudlevy j'ai l'impression que ça a été fait, l'issue est tjrs d'actualité ?

**Comment by Olivia206** [comment]
J'ai fait le balisage de l'index des volumes publiés ([ici](https://github.com/noesya/osuny-hugo-theme-aaa/commit/ac878bc0c3ac12c36ec9b362f652065c79726b45)), est-ce que ça te convient ?

**Comment by arnaudlevy** [comment]
Oui ça a l'air chouette ! je savais pas qu'on pouvait mettre 2 itemtypes :)

**Comment by Olivia206** [comment]
C'est à dire ?
Est-ce qu'un article a un itemtype implicite ? Si c'est le cas je ne savais pas !

**Comment by arnaudlevy** [comment]
Les papers, les articles de revues scientifiques 😃
